### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by ShaffySwitcher** [spacebanana420/Andromeda-Password-Manager#1]
Can't run on Windows, due to Bash not being accessible without third-parties.

**Comment by spacebanana420** [comment]
Bash, Lua and zip/unzip all have a Windows build, but the main script depends on GNU coreutils or Busybox utils so porting to Windows would mean rewriting the script from scratch, which I won't do because I mainly wrote this utility for Linux desktop and server administration
